### ISSUE TITLE
当页面空间不容纳mini-block时，被整体放在下一页是否应该带上page-header？

### ISSUE THREAD

**Issue by binlvtop** [attacking/print-kit#1]
- version 2.1.2

包括group-header、page-header等公共部分，目前版本当mini-block被整体放在新页时不会带上header，是否考虑优化下？

**Comment by Chris-Kin** [comment]
> * version 2.1.2
> 
> 包括group-header、page-header等公共部分，目前版本当mini-block被整体放在新页时不会带上header，是否考虑优化下？

已修复此问题@2.1.3
